# Generated by Django 4.1 on 2022-11-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
