# Generated by Django 4.1 on 2022-12-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libApp', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_types',
            field=models.CharField(choices=[('Education', 'education'), ('Mangas', 'mangas'), ('MM_Books', 'mm_books'), ('History', 'history'), ('Health', 'health'), ('Novel', 'novel')], max_length=200),
        ),
    ]
